name: wekan-117

on:
  push:
    branches:
      - 'master'
      - 'podman'
    paths:
      - Dockerfile-alpine

jobs:
  build:
    name: Build and push image
    environment: production
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Get image tags
      id: image_tags
      run: |
        echo -n ::set-output name=IMAGE_TAGS::
        if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
            echo ${BASH_REMATCH[1]}
        else
            echo ${{ github.sha }}
        fi

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: wekan
        build-args: TIMEZONE=Asia/Shanghai
        tags: ${{ steps.image_tags.outputs.IMAGE_TAGS }}
        archs: amd64, arm64
        context: ./
        containerfiles: Dockerfile-alpine

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags:  ${{ steps.build-image.outputs.tags }}
        registry: quay.io/${{ secrets.REGISTRY_USERNAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
