name: build-and-publish-wekan

on:
  push:
    branches:
      - 'master'
      - 'feat-subpath'

jobs:
  docker:
    name: Build and push wekan image to quay.io
    environment: production
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
              echo ${BASH_REMATCH[1]}
          else
              echo ${{ github.sha }}
          fi

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: schnell18/wekan:${{ steps.image_tags.outputs.IMAGE_TAGS }}
